export const RESET_REDUX_FOR_SHOP_DETAIL = "RESET_FOR_SHOP_DETAIL"
export const RESET_REDUX_FOR_RATING = "RESET_REDUX_FOR_RATING"
export const RESET_REDUX_FOR_SHOP_MANAGEMENT = "RESET_REDUX_FOR_SHOP_MANAGEMENT"